on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 📂 Sync files
      uses: milanmk/actions-file-deployer@master
      with:
        remote-host: ${{ secrets.SERVER }}
        remote-user: ${{ secrets.USERNAME }}
        remote-password: ${{ secrets.PASSWORD }}
        remote-path: ${{ secrets.DEST }}
        sync: full
